### ISSUE TITLE
Decal rendering is fubared at times, not sure why

### ISSUE THREAD

**Issue by ensiform** [ensiform/ETe#20]
Many surfaces they just seem to not appear at all, whether because of cull or not I am not 100% positive. And even if culling is involved, why is it culling when it should be valid surfaces.

**Comment by tsiren** [comment]
Is there a video available?

**Comment by tsiren** [comment]
https://www.youtube.com/watch?v=XqHHrH2016w

**Comment by ensiform** [comment]
Fixed in PR #31
