### ISSUE TITLE
Permissions Issues

### ISSUE THREAD

**Issue by Joeao** [ensiform/ETe#25]
I'm getting issues that seem to be related to permissions when running the latest test version of ETe (Oct012018).

![etf fileforhandle error](https://user-images.githubusercontent.com/2255423/46411300-b5075080-c71b-11e8-8c6e-c3fb08d6d402.gif)
ETe.exe crashes when loading a server with the error message `fileForHandle: 0`.

This seems to be a permissions issue as running as Administrator causes this issue to disappear.

On a related note, I'm unable to run `/condump filename.txt` with this release, whereas ET.exe has no issues.

The permissions seem to be the same on both ET.exe and ETe.exe, so I'm assuming this is an ETe issue.

**Comment by ensiform** [comment]
If you're running from program files that's your permission issue.

**Comment by ensiform** [comment]
Can you launch the game with +set logfile 2 to your launch shortcut /batch

**Comment by Joeao** [comment]
False alarm. Malwarebytes was causing the issue, sorry.

**Comment by ensiform** [comment]
So you are able to join the server now?
