### ISSUE TITLE
44k sound

### ISSUE THREAD

**Issue by coroner-gss** [ensiform/ETe#35]
I tried running TC:CQB with ETe. Vast performance improvement. I am impressed.
I think the sound cannot be changed to 44k or is s_khz not the right cvar?

On a sidenote: ET uses some lookup table with relatively few entries instead of calculating the angular dependent light shading on models. This results in some ugly artifacts on moving models, e.g. the player models. In my own compile I changed the lookup table to much more entries, 64 or so. Looks much better. Just as a suggestion.

Great work.

**Comment by ensiform** [comment]
44k sounds are not available on purpose due to slower performance IIRC (from q3e and that q3 has no 44k sounds). Are you saying that the mod uses those level of sounds?

**Comment by coroner-gss** [comment]
Hi there. The stock ET engine supports 44k sound (Q3 not but most later derivatives). So I don't know why to deviate from this. 44k might be restricted in the stock cgame but the engine should have no limitation. Truecombat uses 44k since the transition to ET.

I will have a look and sent more details about the shading. I don't have discord yet.

**Comment by ensiform** [comment]
Fixed in https://github.com/ensiform/ETe/commit/08b14df0f35a92dbf1aa152d3c43de65082e02f0

Changed light steps in https://github.com/ensiform/ETe/commit/a278abe82a55fde047fcb9111c998515d5fd00f4
